require "rails_helper"

RSpec.describe UpcItem do
  it "exists" do
    attrs = {
      "added_time": "2022-09-07 01:57:53",
      "modified_time": "2022-09-07 01:57:53",
      "title": "Seasoned asian medley",
      "alias": nil,
      "description": "Seasoned asian medley",
      "brand": "",
      "manufacturer": nil,
      "msrp": nil,
      "ASIN": nil,
      "category": "Food",
      "categories": "Plant-based foods and beverages, Plant-based foods, Fruits and vegetables based foods, Frozen foods, Vegetables based foods, Frozen plant-based foods, Frozen vegetables",
      "stores": nil,
      "barcode": "0014500021632",
      "success": true,
      "timestamp": 1706306010,
      "images": nil,
      "metadata": {
          "countries": "United States",
          "ingredients": "Carrots, broccoli, baby cob corn, sugar snap peas, 2% or less: soybean oil, salt, sugar, natural flavor, dehydrated onion, dehydrated garlic, spice."
      },
      "metanutrition": {
          "fat": "1.95",
          "salt": "0.8525",
          "fiber": "2.6",
          "energy": "272",
          "sodium": "0.341",
          "sugars": "5.19",
          "fat_100g": "1.95",
          "fat_unit": "g",
          "proteins": "1.3",
          "fat_value": "1.95",
          "iron_unit": "mg",
          "potassium": "0.247",
          "salt_100g": "0.8525",
          "salt_unit": "mg",
          "vitamin-a": "0.0002646",
          "vitamin-c": "0.0176",
          "fiber_100g": "2.6",
          "fiber_unit": "g",
          "nova-group": "4",
          "salt_value": "852.5",
          "energy-kcal": "65",
          "energy_100g": "272",
          "energy_unit": "kcal",
          "fat_serving": "1.5",
          "fiber_value": "2.6",
          "sodium_100g": "0.341",
          "sodium_unit": "mg",
          "sugars_100g": "5.19",
          "sugars_unit": "g",
          "calcium_unit": "mg",
          "energy_value": "65",
          "salt_serving": "0.656",
          "sodium_value": "341",
          "sugars_value": "5.19",
          "carbohydrates": "10.39",
          "fiber_serving": "2",
          "proteins_100g": "1.3",
          "proteins_unit": "g",
          "energy_serving": "209",
          "potassium_100g": "0.247",
          "potassium_unit": "mg",
          "proteins_value": "1.3",
          "sodium_serving": "0.263",
          "sugars_serving": "4",
          "trans-fat_unit": "g",
          "vitamin-a_100g": "0.0002646",
          "vitamin-a_unit": "IU",
          "vitamin-c_100g": "0.0176",
          "vitamin-c_unit": "mg",
          "nova-group_100g": "4",
          "potassium_value": "247",
          "vitamin-a_value": "882",
          "vitamin-c_value": "17.6",
          "cholesterol_unit": "mg",
          "energy-kcal_100g": "65",
          "energy-kcal_unit": "kcal",
          "proteins_serving": "1",
          "energy-kcal_value": "65",
          "potassium_serving": "0.19",
          "vitamin-a_serving": "0.000204",
          "vitamin-c_serving": "0.0136",
          "carbohydrates_100g": "10.39",
          "carbohydrates_unit": "g",
          "nova-group_serving": "4",
          "nutrition-score-fr": "-3",
          "saturated-fat_unit": "g",
          "carbohydrates_value": "10.39",
          "energy-kcal_serving": "50.1",
          "carbohydrates_serving": "8",
          "nutrition-score-fr_100g": "-3",
          "fruits-vegetables-nuts-estimate-from-ingredients_100g": "11.090909090909",
          "fruits-vegetables-nuts-estimate-from-ingredients_serving": "11.090909090909"
      }
    }

    user_allergies = {
      "ghee"=>true,
      "milk"=>true,
      "whey"=>true,
      "cream"=>true,
      "curds"=>true,
      "butter"=>true,
      "casein"=>true,
      "cheese"=>true,
      "nougat"=>true,
      "paneer"=>true,
      "yogurt"=>true,
      "lactose"=>true,
      "milk fat"=>true,
      "caseinate"=>true,
      "goat milk"=>true,
      "lactulose"=>true,
      "recaldent"=>true,
      "skim milk"=>true,
      "butter fat"=>true,
      "butter oil"=>true,
      "buttermilk"=>true,
      "sheep milk"=>true,
      "sour cream"=>true,
      "sweet whey"=>true,
      "whole milk"=>true,
      "goat cheese"=>true,
      "half & half"=>true,
      "lactalbumin"=>true,
      "lactoferrin"=>true,
      "malted milk"=>true,
      "milk powder"=>true,
      "milk solids"=>true,
      "nonfat milk"=>true,
      "whey powder"=>true,
      "low-fat milk"=>true,
      "milk protein"=>true,
      "butter esters"=>true,
      "butter solids"=>true,
      "lactoglobulin"=>true,
      "rennet casein"=>true,
      "whipped cream"=>true,
      "condensed milk"=>true,
      "cottage cheese"=>true,
      "iron caseinate"=>true,
      "zinc caseinate"=>true,
      "delactosed whey"=>true,
      "dry milk powder"=>true,
      "dry milk solids"=>true,
      "evaporated milk"=>true,
      "milk derivative"=>true,
      "whipped topping"=>true,
      "acidophilus milk"=>true,
      "sodium caseinate"=>true,
      "sour milk solids"=>true,
      "buttermilk powder"=>true,
      "calcium caseinate"=>true,
      "hydrolyzed casein"=>true,
      "sheep milk cheese"=>true,
      "ammonium caseinate"=>true,
      "demineralized whey"=>true,
      "potasium caseinate"=>true,
      "magnesium caseinate"=>true,
      "natural Butter flavor"=>true,
      "hydrolyzed milk protein"=>true,
      "sweetened condensed milk"=>true,
      "whey protein concentrate"=>true,
      "whey protein hydrolysate"=>true,
      "hsp"=>true,
      "msg"=>true,
      "soy"=>true,
      "tsf"=>true,
      "tsp"=>true,
      "tvp"=>true,
      "miso"=>true,
      "soya"=>true,
      "tofu"=>true,
      "yuba"=>true,
      "carob"=>true,
      "natto"=>true,
      "okara"=>true,
      "supro"=>true,
      "tamari"=>true,
      "tempeh"=>true,
      "edamame"=>true,
      "gelatin"=>true,
      "kyodofu"=>true,
      "soybean"=>true,
      "lecithin"=>true,
      "licorice"=>true,
      "soy bean"=>true,
      "soy bran"=>true,
      "soy milk"=>true,
      "soy miso"=>true,
      "soy nuts"=>true,
      "soy pulp"=>true,
      "soybeans"=>true,
      "teriyaki"=>true,
      "yakidofu"=>true,
      "bean curd"=>true,
      "soy beans"=>true,
      "soy fiber"=>true,
      "soy flour"=>true,
      "soy grits"=>true,
      "soy sauce"=>true,
      "fish sauce"=>true,
      "soya flour"=>true,
      "glycine max"=>true,
      "shoyu sauce"=>true,
      "soy albumin"=>true,
      "soy formula"=>true,
      "soy sprouts"=>true,
      "oyster sauce"=>true,
      "soybean curd"=>true,
      "kinnoko flour"=>true,
      "soybean paste"=>true,
      "soy nut butter"=>true,
      "autolyzed yeast"=>true,
      "soy concentrate"=>true,
      "soybean granules"=>true,
      "soy isolate fiber"=>true,
      "textured soy flour"=>true,
      "mono & diglycerides"=>true,
      "soy protein isolate"=>true,
      "monosodium glutamate"=>true,
      "textured soy protein"=>true,
      "hydrolyzed soy protein"=>true,
      "soy protein concentrate"=>true,
      "textured vegetable protein"=>true
    }

    item = UpcItem.new(attrs, "014500021632", user_allergies)

    expect(item.name).to eq("Seasoned Asian Medley")
    expect(item.upc_code).to eq("014500021632")
    expect(item.ingredients).to eq(["Carrots", "Broccoli", "Baby Cob Corn", "Sugar Snap Peas", "2% Or Less: Soybean Oil", "Salt", "Sugar", "Natural Flavor", "Dehydrated Onion", "Dehydrated Garlic", "Spice"])
    expect(item.allergens).to eq(["2% Or Less: Soybean Oil"])
    expect(item.lily_eat).to eq(false)
  end
end